### ISSUE TITLE
Add link to the website on the organization page

### ISSUE THREAD

**Issue by stof** [php-pds/php-pds.github.io#1]
It may be worth adding the link to http://php-pds.com/ on the organization page on github

**Comment by pmjones** [comment]
Done; thanks.

**Comment by stof** [comment]
the organization page still does not have the link: https://github.com/php-pds
![php-pds_org](https://cloud.githubusercontent.com/assets/439401/22376758/90260310-e4af-11e6-89b4-13d5bc9cac9f.png)

**Comment by pmjones** [comment]
Aha! I put it on the php-pds.github.io repo page. I have added it to the *org* page now. Thanks for the followup correction!

**Comment by stof** [comment]
Well, having it on the website repo makes sense as well indeed.
